### PR TITLE
Update asu_news.settings.yml

### PR DESCRIPTION
**Pull request by niner9**
Change the asu_news_feed_url to the correct/current website address.

### CODE REVIEW

**Comment by mlsamuelson** [comment]
@imorale2 @chill5-0 Do either of you know if there's a ticket related to this? And/or want to review?

**Comment by chill5-0** [comment]
@mlsamuelson @imorale2  - I think this might be related to this ticket? https://asudev.jira.com/browse/WASC-914 
It looks like asunow is a redirecting to the new URL so I this update is aligning the module code.

**Comment by mlsamuelson** [comment]
Hi @niner9 can you confirm?

**Comment by niner9** [comment]
Yes.  This is correct.

**Review by mlsamuelson — CHANGES_REQUESTED** [review]
@niner9 Thanks. This looks good, but we need one additional piece in place - if you could add the following to the `asu_news.install` file around line 36 it will ensure the update gets felt by existing sites other than just those installing new:

```
/**
 * Implements hook_update_N();
 * Revert all the module config.
 */
function asu_news_update_9004(&$sandbox) {
  _asu_news_revert_all_module_config();
}
```
Note: I incremented the update number here, so this code should be good to go. If you could add it to the PR, I think we're good to go.

**Review by mlsamuelson — APPROVED** [review]
@niner9 Woot! Thanks for the PR, Brandon.

cc @chill5-0 👍🏼

**Pull request merged**
